# Generated by Django 4.2.11 on 2024-04-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soilRegenApp', '0003_alter_ingredient_practice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unit',
            table='unit',
        ),
    ]
